import json
import os
import pandas as pd
from config import NEIGHBORHOODS, PROCESSED_DATA_DIR
from scoring import calculate_scores, generate_insights

def export_to_js(df, output_path='site/data.js'):
    """Export scored DataFrame to data.js for the dashboard."""
    
    areas = []
    for _, row in df.iterrows():
        name = row['neighborhood']
        bbox = NEIGHBORHOODS.get(name, {})
        
        # Create polygon for Leaflet [lat, lng] format
        if bbox:
            sw_lat, sw_lng = bbox['sw']
            ne_lat, ne_lng = bbox['ne']
            polygon = [
                [sw_lat, sw_lng], [sw_lat, ne_lng],
                [ne_lat, ne_lng], [ne_lat, sw_lng]
            ]
        else:
            polygon = []
        
        area = {
            'name': name,
            'lat': round(float(row.get('lat', 0)), 4),
            'lng': round(float(row.get('lng', 0)), 4),
            'polygon': polygon,
            'heat_score': round(float(row.get('heat_score', 0)), 1),
            'population': int(row.get('population', 0)),
            'tree_cover_pct': int(row.get('tree_cover_pct', 0)),
            'pavement_pct': int(row.get('pavement_pct', 0)),
            'pop_score': round(float(row.get('pop_score', 0)), 1),
            'tree_score': round(float(row.get('tree_score', 0)), 1),
            'pavement_score': round(float(row.get('pavement_score', 0)), 1),
            'elderly_pct': int(row.get('elderly_pct', 0)),
            'children_pct': int(row.get('children_pct', 0)),
            'median_income': int(row.get('median_income', 0)),
            'park_area_acres': int(row.get('park_area_acres', 0)),
            'heat_index_c': round(float(row.get('heat_index_c', 0)), 1) if 'heat_index_c' in row and pd.notna(row['heat_index_c']) else None,
            'apparent_temp_c': round(float(row.get('apparent_temp_c', 0)), 1) if 'apparent_temp_c' in row and pd.notna(row['apparent_temp_c']) else None,
            'humidity_pct': int(row.get('humidity_pct', 0)) if 'humidity_pct' in row and pd.notna(row['humidity_pct']) else None,
            'aqi': int(row.get('aqi', 0)) if 'aqi' in row and pd.notna(row['aqi']) else None,
            'wet_bulb_c': round(float(row.get('wet_bulb_c', 0)), 1) if 'wet_bulb_c' in row and pd.notna(row['wet_bulb_c']) else None,
            'solar_ghi': int(row.get('solar_ghi', 0)) if 'solar_ghi' in row and pd.notna(row['solar_ghi']) else None,
            'buildings_pct': int(row.get('buildings_pct', 0)),
            'roads_pct': int(row.get('roads_pct', 0)),
            'vegetation_pct': int(row.get('vegetation_pct', 0)),
            'bare_soil_pct': int(row.get('bare_soil_pct', 0)),
            'water_pct': int(row.get('water_pct', 0)),
            'impervious_pct': int(row.get('impervious_pct', 0)),
            'day_temp_c': round(float(row.get('day_temp_c', 0)), 1) if 'day_temp_c' in row and pd.notna(row['day_temp_c']) else None,
            'day_temp_f': round(float(row.get('day_temp_f', 0)), 1) if 'day_temp_f' in row and pd.notna(row['day_temp_f']) else None,
            'night_temp_c': round(float(row.get('night_temp_c', 0)), 1) if 'night_temp_c' in row and pd.notna(row['night_temp_c']) else None,
            'night_temp_f': round(float(row.get('night_temp_f', 0)), 1) if 'night_temp_f' in row and pd.notna(row['night_temp_f']) else None,
            'night_heat_score': round(float(row.get('night_heat_score', 0)), 1) if 'night_heat_score' in row and pd.notna(row['night_heat_score']) else None,
            'data_source': row.get('data_source', 'open-meteo'),
        }
        areas.append(area)
    
    insights = generate_insights(df)
    
    js_content = f"""// HeatShield Dashboard Data
// Auto-generated by export_to_dashboard.py
// Last updated: {pd.Timestamp.now().strftime('%Y-%m-%d %H:%M')}

const AREAS = {json.dumps(areas, indent=2)};

const DEFAULT_WEIGHTS = {{ heat: 50, population: 25, tree_cover: 15, pavement: 10 }};

const CITY = {{ name: 'Los Angeles, CA', center: [34.0522, -118.2437], zoom: 11 }};

const INSIGHTS = {json.dumps(insights, indent=2)};
"""
    
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(js_content)
    
    print(f' Dashboard data exported to {output_path}')
    print(f'   {len(areas)} areas, {len(insights)} insights')

if __name__ == '__main__':
    csv_path = os.path.join(PROCESSED_DATA_DIR, 'master_dataset_la.csv')
    if os.path.exists(csv_path):
        df = pd.read_csv(csv_path)
        df = calculate_scores(df)
        export_to_js(df)
    else:
        print('No master dataset. Run build_master_dataset.py first.')
